nome = str(input('Digite seu nome:'))
idade = int(input('Agora digite sua idade:'))
cidade = str(input('Digite o nome da sua cidade:'))
print('Olá ',nome)
print('Você tem ',idade)
print('Você mora em', cidade)
